.retag:
  stage: package
  image: docker.io/regclient/regctl:v0.9.2-alpine
  variables:
    GIT_STRATEGY: none
    REGCTL_CONFIG: $CI_PROJECT_DIR/.regctl/config.json
  before_script:
    - export REG_HOST=${INTERNAL_REG%/*}
    - mkdir -p "$(dirname "$REGCTL_CONFIG")"
    - >
      echo "{\"hosts\":{\"${REG_HOST}\":{\"tls\":\"enabled\",\"hostname\":
      \"${REG_HOST}\",\"user\":\"${IMAGE_REGISTRY_USER}\",\"pass\":
      \"${IMAGE_REGISTRY_PASS}\"}}}" >> $REGCTL_CONFIG
  script:
    - >
      regctl --verbosity info image copy
      "${IMAGE_NAME}-unverified" "${IMAGE_NAME}"
    - regctl tag delete "${IMAGE_NAME}-unverified" || echo "Tag already deleted"

ckan-retag:
  needs:
    - set-vars
    - ckan-scan
  extends:
    - .triggers    
    - .retag
  variables:
    IMAGE_NAME: ${CKAN_IMAGE}

proxy-retag:
  needs:
    - set-vars
    - proxy-scan
  extends:
    - .triggers    
    - .retag
  variables:
    IMAGE_NAME: ${PROXY_IMAGE}

