include:
  - local: '.gitlab-ci-scan.yml'
  - local: '.gitlab-ci-package.yml'

stages:
  - build
  - scan
  - package
  - deploy
  - release
  - manual-deploy
  
variables:
  ARTIFACT_COMPRESSION_LEVEL: "fast" ## check if required
  CACHE_COMPRESSION_LEVEL: "fast" ## check if required

.triggers:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success
    - if: $CI_COMMIT_REF_NAME == "staging"
      when: on_success
    - if: $CI_COMMIT_REF_NAME == "dev"
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: on_success

set-vars:
  stage: .pre
  environment: $CI_COMMIT_REF_NAME
  image: docker.io/alpine:3.20
  script:
    - echo "$CKAN_ENV" | grep '^CKAN_VERSION=' >> build.env
    - . build.env
    - "echo APP_NAME=ckan-${CI_COMMIT_REF_NAME} >> build.env"
    # - echo "NAMESPACE=ckan" >> build.env
    # - echo CHART_VERSION=$(yq '.version' chart/Chart.yaml) >> build.env
    - "echo CKAN_IMAGE=${INTERNAL_REG}/ckan-docker-envidat/ckan:\
      ${CKAN_VERSION}-${CI_COMMIT_REF_NAME} >> build.env"
    - "echo PROXY_IMAGE=${INTERNAL_REG}/ckan-docker-envidat/proxy:\
      nginx-${CI_COMMIT_REF_NAME} >> build.env"
    - echo "Printing build.env"
    - cat build.env
  artifacts:
    reports:
      dotenv: build.env

.build:
  stage: build
  image: docker:24.0.5
  needs:
    - set-vars
  services:
    - name: docker:24.0.5-dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_AUTH_CONFIG: $DOCKER_AUTH_CONFIG
  tags:
    - dind
  before_script:
    - echo "Waiting for Docker daemon..."
    - until docker info >/dev/null 2>&1; do sleep 1; done
    # Auth with DOCKER_AUTH_CONFIG if present
    #- |
    #  if [ -n "$DOCKER_AUTH_CONFIG" ]; then
    #    echo "Using DOCKER_AUTH_CONFIG for authentication"
    #    mkdir -p ~/.docker
    #    echo "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json
    #  else
    #    echo "Logging in to registry $CI_REGISTRY with provided credentials"
    #    echo "$IMAGE_REGISTRY_PASSWORD" | docker login -u "$IMAGE_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    #  fi
    - mkdir -p ~/.docker
    - echo "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json
    - docker info
  script:
    - echo "Check how the filesystem looks like for debugging"
    - ls -a
    - echo "CKAN_VERSION=$CKAN_VERSION"
    - echo "CKAN_IMAGE=$CKAN_IMAGE"
    - echo "CONTEXT_DIR=$CONTEXT_DIR"
    - docker build -t "${IMAGE_NAME}-unverified" -f "${CONTEXT_DIR}/Dockerfile" "${CONTEXT_DIR}"
    - docker info
    - docker images
    - docker logout "$CI_REGISTRY"
    - echo "$IMAGE_REGISTRY_PASSWORD" | docker login -u "$IMAGE_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker whoami   # For newer docker versions (plugin) — if not available, use:
    - cat ~/.docker/config.json
    - docker push "${IMAGE_NAME}-unverified"
    #- docker run my-docker-image /script/to/run/tests

#.build:
#  image: moby/buildkit
#  stage: build
#  variables:
#    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
#    DOCKER_AUTH_CONFIG: $DOCKER_AUTH_CONFIG
#    GIT_STRATEGY: clone
#  before_script:
#    - mkdir -p ~/.docker
#    - echo "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json
#  script:
#    - |
#      buildctl-daemonless.sh build \
#        --frontend dockerfile.v0 \
#        --local context="$CONTEXT_DIR" \
#        --local dockerfile="$CONTEXT_DIR" \
#        --output type=image,name="$IMAGE_NAME",push=true

ckan-build:
  extends:
    - .triggers
    - .build
  variables:
    IMAGE_NAME: ${CKAN_IMAGE}
    CONTEXT_DIR: "${CI_PROJECT_DIR}/ckan"

proxy-build:
  extends:
    - .triggers
    - .build
  cache:
    key: nginx-config
    paths:
      - nginx/conf.d/ckan.conf.template
    policy: pull
  variables:
    IMAGE_NAME: ${PROXY_IMAGE}
    CONTEXT_DIR: "${CI_PROJECT_DIR}/nginx"

#db-build:
#  extends:
#    - .triggers
#    - .build
#  variables:
#    IMAGE_NAME: ${DB_IMAGE}
#    CONTEXT_DIR: "${CI_PROJECT_DIR}/postgresql"

remote-docker:
  stage: deploy
  environment: $CI_COMMIT_REF_NAME
  image: docker.io/docker:24.0
  extends:
    - .triggers
  needs:
    - set-vars
    - ckan-retag
    - proxy-retag
  variables:
    DOCKER_HOST: "ssh://$DEPLOY_SSH_USER@$DEPLOY_HOSTNAME"
  before_script:
    - echo "***The app image is   ${IMAGE_NAME}"
    - echo "***The app version is  ${CKAN_VERSION}"
    - echo "Going to docker remote ($DEPLOY_HOSTNAME) with file docker-compose.$CI_COMMIT_REF_NAME.yml"
    - echo "$CKAN_ENV" > .env
    - echo "Adding SSH Key"
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SSH_KEY" > ~/.ssh/gitlab
    - chmod 400 ~/.ssh/gitlab
    - echo 'IdentityFile ~/.ssh/gitlab' > ~/.ssh/config
    - echo "going to keyscan on HOST ${DEPLOY_HOSTNAME}"
    - ssh-keyscan -H $DEPLOY_HOSTNAME >> ~/.ssh/known_hosts
  #    - cat ~/.ssh/known_hosts
  script:
    - |
      USER_DIR=$(echo "/home/$DEPLOY_SSH_USER")
      ssh "$DEPLOY_SSH_USER@$DEPLOY_HOSTNAME" "mkdir -p $USER_DIR/config/ckan"
      scp .env "$DEPLOY_SSH_USER@$DEPLOY_HOSTNAME:$USER_DIR/config/ckan/.env"
    - HOME=$USER_DIR
    #- echo "going to docker login with user ${DOCKER_USERNAME}"
    #- echo "${DOCKER_TOKEN}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    # use docker compose create to recreate the container and force pulling the latest image
    # to avoid using the local cache
    - |
      docker compose --project-name="$APP_NAME" \
        create --force-recreate --pull="always"
    # use docker compose up to start the service on the remote machine
    - |
      docker compose --project-name="$APP_NAME" up --detach

# Job for manual deploying of a docker-compose file, to use it's
# docker images, make sure before you run it that the images referenced
# in the docker-compose.$CI_COMMIT_REF_NAME.yml exist!
manual-remote-docker:
  stage: manual-deploy
  environment: $CI_COMMIT_REF_NAME
  image: docker.io/docker:24.0
  needs:
    - set-vars
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      when: always
    - when: manual
  # for manaul jobs add allow_failure so the whole pipeline won't show up as "blocked"
  allow_failure: true    
  variables:
    DOCKER_HOST: "ssh://$DEPLOY_SSH_USER@$DEPLOY_HOSTNAME"
  before_script:
    - echo "$CKAN_ENV" > .env
    - echo "Adding SSH Key"
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SSH_KEY" > ~/.ssh/gitlab
    - chmod 400 ~/.ssh/gitlab
    - echo 'IdentityFile ~/.ssh/gitlab' > ~/.ssh/config
    - echo "going to keyscan on HOST ${DEPLOY_HOSTNAME}"
    - ssh-keyscan -H $DEPLOY_HOSTNAME >> ~/.ssh/known_hosts
#    - cat ~/.ssh/known_hosts
  script:
    - USER_DIR=$(echo "/home/$DEPLOY_SSH_USER")
    - echo "Defined USER_DIR ${USER_DIR}"
    - echo "Going to create the config/ckan directory for the .env file"
    - ssh "$DEPLOY_SSH_USER@$DEPLOY_HOSTNAME" "mkdir -p $USER_DIR/config/ckan"
    - ls -la
    - echo "Going to copy the local ckan.ini file to ${USER_DIR}/config/ckan/.env"
    - scp .env "$DEPLOY_SSH_USER@$DEPLOY_HOSTNAME:$USER_DIR/config/ckan/.env"
    - HOME=$USER_DIR
    - echo "Going to remotely start the docker-compose.${CI_COMMIT_REF_NAME}.yml on ${DEPLOY_SSH_USER}@${DEPLOY_HOSTNAME}"
    #- echo "going to docker login with user ${DOCKER_USERNAME}"
    #- echo "${DOCKER_TOKEN}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    # use docker compose create to recreate the container and force pulling the latest image
    # to avoid using the local cache
    - |
      docker compose --project-name="$APP_NAME" \
        create --force-recreate --pull="always"
    # use docker compose up to start the service on the remote machine
    - |
      docker compose --project-name="$APP_NAME" up --detach

build-binary:
  stage: release
  image: docker.io/debian:bookworm
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - apt update && apt install -y curl
    - curl -LO https://github.com/ajdiaz/bashc/releases/download/5.2.15/bashc
    - chmod +x bashc
  script:
    - ./bashc scripts/envidat-in-a-box.sh envidat
  after_script:
    - echo "BIN_JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    paths:
      - envidat
    expire_in: never
    reports:
      dotenv: job.env

release-binary:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build-binary
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job for $CI_COMMIT_TAG"
    - echo "Using artifact from job $BIN_JOB_ID"
  release:
    name: "Release $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: envidat-in-a-box
          url: $CI_SERVER_URL/$CI_PROJECT_PATH/-/jobs/$BIN_JOB_ID/artifacts/raw/envidat
