FROM ckan/ckan-dev:2.11

# Install any extensions needed by your CKAN instance
# - Make sure to add the plugins to CKAN__PLUGINS in the .env file
# - Also make sure all provide all extra configuration options, either by:
#   * Adding them to the .env file (check the ckanext-envvars syntax for env vars), or
#   * Adding extra configuration scripts to /docker-entrypoint.d folder) to update
#      the CKAN config file (ckan.ini) with the `ckan config-tool` command
#
# See README > Extending the base images for more details
#
# For instance:
#
### XLoader ###
#RUN pip3 install -e 'git+https://github.com/ckan/ckanext-xloader.git@master#egg=ckanext-xloader' && \ 
#    pip3 install -r ${APP_DIR}/src/ckanext-xloader/requirements.txt && \
#    pip3 install -U requests[security]

### Harvester ###
#RUN pip3 install -e 'git+https://github.com/ckan/ckanext-harvest.git@master#egg=ckanext-harvest' && \
#    pip3 install -r ${APP_DIR}/src/ckanext-harvest/pip-requirements.txt
# will also require gather_consumer and fetch_consumer processes running (please see https://github.com/ckan/ckanext-harvest)

### Scheming ###
#RUN  pip3 install -e 'git+https://github.com/ckan/ckanext-scheming.git@master#egg=ckanext-scheming'

### Pages ###
#RUN  pip3 install -e git+https://github.com/ckan/ckanext-pages.git#egg=ckanext-pages

### DCAT ###
#RUN  pip3 install -e git+https://github.com/ckan/ckanext-dcat.git@v0.0.6#egg=ckanext-dcat && \
#     pip3 install -r https://raw.githubusercontent.com/ckan/ckanext-dcat/v0.0.6/requirements.txt

# Clone the extension(s) your are writing for your own project in the `src` folder
# to get them mounted in this image at runtime


############################ Extensions used by EnviDat CKAN ###########################

# TODO possibly reimplement after ckanext-spatial is updated
# Installation compatible with customized envidat ckanext-spatial extension
# Install libgeos-dev so that the dependencies of ckanext-spatial can be installed
# USER root
# RUN apt-get update && apt-get install -y \
#    libgeos-dev \
#    gdal-bin \
#    && rm -rf /var/lib/apt/lists/*
# USER ckan

# TODO possibly remove installation below after ckanext-spatial is updated
# Install packages needed by official ckanext-scheming extension
USER root
RUN apt-get update && apt-get install -y \
    libxml2-dev \
    libxslt1-dev \
    libgeos-dev \
    && rm -rf /var/lib/apt/lists/*
USER ckan

# passwordless_api
RUN pip install -e git+https://gitlabext.wsl.ch/EnviDat/ckanext-passwordless_api.git@main#egg=ckanext-passwordless_api

# scheming
RUN pip install -e git+https://github.com/ckan/ckanext-scheming.git@master#egg=ckanext-scheming

# TODO implement
# envidat_theme (has schemas used by ckanext-scheming)
WORKDIR /srv/app/src
RUN git clone --branch ckan-2-11 https://gitlabext.wsl.ch/EnviDat/ckan_extensions/ckanext-envidat_theme.git /srv/app/src/ckanext-envidat_theme
RUN pip install -e /srv/app/src/ckanext-envidat_theme

# TODO decide if upgrading extension or using standard version
# spatial (has snippets used by ckanext-envidat_theme)
# RUN git clone https://gitlabext.wsl.ch/EnviDat/ckan_extensions/ckanext-spatial.git /srv/app/src/ckanext-spatial
# RUN pip install -e /srv/app/src/ckanext-spatial
# RUN pip install -r /srv/app/src/ckanext-spatial/requirements.txt

# spatial
RUN pip install -e git+https://github.com/ckan/ckanext-spatial.git@master#egg=ckanext-spatial
RUN pip install -r /srv/app/src/ckanext-spatial/requirements.txt

# TODO test
# composite (used by "datacite_dataset.json" in ckanext-envidat_theme)
RUN pip install -e git+https://gitlabext.wsl.ch/EnviDat/ckan_extensions/ckanext-composite.git@master#egg=ckanext-composite

# TODO possibly remove as functionality used has been replaced in ckanext-envidat_theme.git@ckan-2-11
# RUN pip install -e git+https://github.com/ckan/ckanext-hierarchy.git#egg=ckanext-hierarchy && \
#    pip install -r ${APP_DIR}/src/ckanext-hierarchy/requirements.txt

# TODO implement and test, add configuration settings
# cloudstorage
# RUN pip install -e git+https://gitlabext.wsl.ch/EnviDat/ckan_extensions/ckanext-cloudstorage@master#egg=ckanext-cloudstorage

# blind_review
RUN pip install -e git+https://gitlabext.wsl.ch/EnviDat/ckanext-blind_review.git@ckan-2-11#egg=ckanext_blind_review

########################################################################################


# Copy custom initialization scripts
COPY --chown=ckan-sys:ckan-sys docker-entrypoint.d/* /docker-entrypoint.d/

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
COPY --chown=ckan-sys:ckan-sys patches ${APP_DIR}/patches

USER ckan

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done
